
resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
  ControlPlaneSubnetCidr: '24'
  ControlPlaneDefaultRoute: 9.1.1.1
  EC2MetadataIp: 9.1.1.1
  ExternalNetCidr: 11.0.0.0/8
  ExternalAllocationPools: [{"start": "11.1.1.111", "end": "11.1.1.123"}]
  ExternalInterfaceDefaultRoute: 11.1.1.1
  NeutronExternalNetworkBridge: "''"
  InternalApiNetCidr: 10.2.2.0/24
  InternalApiAllocationPools: [{"start": "10.2.2.10", "end": "10.2.2.200"}]
  InternalApiNetworkVlanID: 2
  StorageNetCidr: 10.3.3.0/24
  StorageAllocationPools: [{"start": "10.3.3.10", "end": "10.3.3.200"}]
  StorageNetworkVlanID: 3
  StorageMgmtNetCidr: 10.4.4.0/24
  StorageMgmtAllocationPools: [{"start": "10.4.4.10", "end": "10.4.4.200"}]
  StorageMgmtNetworkVlanID: 4
  TenantNetCidr: 10.5.5.0/24
  TenantAllocationPools: [{"start": "10.5.5.10", "end": "10.5.5.200"}]
  TenantNetworkVlanID: 5
  DnsServers: ["11.1.1.1", "8.8.4.4"]
