
resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
  ControlPlaneSubnetCidr: '24'
  ControlPlaneDefaultRoute: 9.1.1.1
  EC2MetadataIp: 9.1.1.1
  ExternalNetCidr: 8.1.1.0/24
  ExternalAllocationPools: [{"start": "8.1.1.10", "end": "8.1.1.50"}]
  ExternalInterfaceDefaultRoute: 8.1.1.1
  NeutronExternalNetworkBridge: "''"
  InternalApiNetCidr: 172.17.0.0/24
  InternalApiAllocationPools: [{"start": "172.17.0.10", "end": "172.17.0.250"}]
  StorageNetCidr: 172.18.0.0/24
  StorageAllocationPools: [{"start": "172.18.0.10", "end": "172.18.0.250"}]
  StorageMgmtNetCidr: 172.19.0.0/24
  StorageMgmtAllocationPools: [{"start": "172.19.0.10", "end": "172.19.0.250"}]
  TenantNetCidr: 172.16.0.0/24
  TenantAllocationPools: [{"start": "172.16.0.10", "end": "172.16.0.250"}]
  DnsServers: ["11.1.1.1", "8.8.4.4"]
